version: "3.9"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8010:8010"
    volumes:
      - ./docs:/app/docs
      - ./chroma:/app/chroma
      - ./rag_debug_fresh.jsonl:/app/rag_debug_fresh.jsonl
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/html
      - ./php:/var/www/html/php
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend

  php:
    image: php:8.1-fpm
    volumes:
      - ./php:/var/www/html/php
      - ./rag_debug_fresh.jsonl:/var/www/html/rag_debug.jsonl

  # Add PostgreSQL service for session and user memory storage
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mobeus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
