version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8010:8010"
    volumes:
      - ./docs:/app/docs
      - ./chroma:/app/chroma
      - ./rag_debug.jsonl:/app/rag_debug.jsonl
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/var/www/html
      - ./php:/var/www/html/php
      - ./rag_debug.jsonl:/var/www/html/rag_debug.jsonl
    depends_on:
      - backend
      - frontend

  php:
    image: php:8.1-fpm
    volumes:
      - ./php:/var/www/html/php
      - ./rag_debug.jsonl:/var/www/html/rag_debug.jsonl
