services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8010:8010"
    volumes:
      - ./backend:/app
      - ./docs:/app/docs
      - ./chroma:/app/chroma
      - ./logs:/app/logs
      - ./init-db:/app/init-db # Database initialization scripts
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      POSTGRES_HOST: postgres
      MOBEUS_DEBUG: "true"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80" # Main app
      - "443:443" # HTTPS (production)
      - "8088:8088" # Admin dashboard
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Production config
      - ./frontend/dist:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro # SSL certificates (production)
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mobeus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d # Database initialization

volumes:
  postgres_data:
