services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8010:8010"
    volumes:
      - ./backend:/app
      - ./docs:/app/docs
      - ./chroma:/app/chroma
      - ./logs:/app/logs
      - ./init-db:/app/init-db # Database initialization scripts
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      POSTGRES_HOST: postgres
      MOBEUS_DEBUG: "true"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mobeus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d # Database initialization

volumes:
  postgres_data:
