version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8010:8010"
    volumes:
      - ./docs:/app/docs
      - ./chroma:/app/chroma
      - ./debug_log.jsonl:/app/debug_log.jsonl
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
