version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8010:8010"
    volumes:
      - ./chroma:/app/chroma # for persistent DB if needed
      - ./debug_log.jsonl:/app/debug_log.jsonl
    environment:
      - - OPENAI_API_KEY=${OPENAI_API_KEY}
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
